### ISSUE TITLE
Various bugs vis components

### ISSUE THREAD

**Issue by dvmartinweigl** [datavisyn/visyn_core#99] opened 2023-10-09 09:47 UTC
In bioinsight we are facing errors within some vis types caused by null values in the data (we have a sparse matrix).
Some components (hexbin plot) even make the whole application crash if invalid data got passed.
Unfortunately it is very hard to check and filter out the null values, because this is based on the current vis config.

@thinkh , @dvmoritzschoefl  and me decided to handle the data cleansing in the vis components itself

#### Here is a list of some null value errors and other small bioinsight related bugs we observed:
- [x] **Bar char** fails in bioinsight if `multiples` column got selected (seems to only happen in production build, to reproduce `yarn run webpack:prod && yarn start dev_server_only=true`)
![image](https://github.com/datavisyn/visyn_core/assets/101096478/7caa56a8-27f6-4a2a-9290-ea4cc41b368b)

- [x] **Violin plot** has misaligned or missing x axis labels after changing the categorical column. Changing the mosaic split size makes the labels render correctly. 
![image](https://github.com/datavisyn/visyn_core/assets/101096478/9b6a616b-a32a-4eb6-8647-f9d63fd51fbd)
 
- [x] **Raincloud plot** actually just needs 1 numerical column. Please change the invalid settings message accordingly.
![image](https://github.com/datavisyn/visyn_core/assets/101096478/36453b48-01a0-41aa-abb8-5ab4445064f6)

- [ ] **Raincloud plot** makes application crash if we set a column with null values only (here EC50) and then change the cloud options

- [x] **Corrialtion plot**: change invalid settings text to _select at least 2 **numerical** columns_
![image](https://github.com/datavisyn/visyn_core/assets/101096478/f251eb24-75c4-48d3-8f0d-72c7da48c662)

- [x] **Scatter plot:** fails on sparse matrix with columns > 2
![Screenshot from 2023-10-09 11-09-57](https://github.com/datavisyn/visyn_core/assets/101096478/aa2077f6-7dbe-4b43-9166-614e7629ab15)

- [x] **Hexbin plot:** application crashes if null values are present in data
![Screenshot from 2023-10-09 11-12-38](https://github.com/datavisyn/visyn_core/assets/101096478/d7f14661-b500-43eb-bbde-ffd016a97283)

- [x] **Hexbin plot**: hide legend if invalid settings
![image](https://github.com/datavisyn/visyn_core/assets/101096478/ead151cf-cb9e-4f8c-b7b3-20bcf59e7402)

- [x] **Correlation plot:** cannot handle integer values
![Screenshot from 2023-10-09 11-27-39](https://github.com/datavisyn/visyn_core/assets/101096478/a7d2d8ad-531f-4a1f-8b07-c8c181bc5d9d)

**Comment by dv-usama-ansari** [comment] 2023-11-16 14:50
Reopening this since the PR #119 closed it automatically

**Comment by dv-usama-ansari** [comment] 2023-11-17 17:20
>  Raincloud plot makes application crash if we set a column with null values only (here EC50) and then change the cloud options

This is not reproducible by me - 

[Screencast from 2023-11-17 18:19:20.webm](https://github.com/datavisyn/visyn_core/assets/115616380/a9cf3e3e-2f05-4947-ad3e-39c1cfd7d4f0)

**Comment by dv-usama-ansari** [comment] 2023-11-20 16:07
Reopening this since the PR https://github.com/datavisyn/visyn_core/pull/122 closed it automatically

**Closed** 2023-11-21 10:55 UTC
Labels: type: bug
